### PR TITLE
Django rewrite

### PR DESCRIPTION
**Pull request by trinkey**
sub you should not just like instantly merge this, instead use this as a place to report bugs or whatever you find to fix

### CODE REVIEW

**Comment by trinkey** [comment]
i believe this is a conclusive list of all issues that will be fixed by this:
1. #44
2. #67
3. #77
4. #78
5. #81
6. #83
7. #84
8. #85
9. #89
10. #96
11. #98
12. #102
13. #103

**Comment by Subroutine7901** [comment]
#80 aswell?

**Comment by Subroutine7901** [comment]
Also thats a good ~14/41 issues solved

**Comment by trinkey** [comment]
> #80 aswell?

false

image

**Comment by trinkey** [comment]
#80 has been added to the list

**Comment by Subroutine7901** [comment]
Ok great, after that we should look for bugs

**Comment by trinkey** [comment]
> Ok great, after that we should look for bugs

yep that's basically all that's left

**Comment by trinkey** [comment]
i meant to say #94 instead of #85 lol

**Comment by trinkey** [comment]
im gonna merge this soon if you're good with that @Subroutine7901 (i'll make a `legacy-flask` branch)

**Pull request merged**
