### PR TITLE
quotes (for #107)

### LINKED ISSUE #107: Quotes
like twitter qrts

Would show another box inside the quote post with the text from the quoted post, clicking on it would bring you to the quoted post. if you quoted a post thats quoting another post, the quoted post would show text saying "Quoting another post" or something offset from the post text to show that there is another quote.

### PR DESCRIPTION
**Pull request by trinkey**
fixes #107

### CODE REVIEW

**Comment by trinkey** [comment]
i still need to add a cancel button but other than that i think its done so @Subroutine7901 itd be great if you could test this out and make sure everything works that would be great

**Comment by trinkey** [comment]
all that needs to be done rn is the x button but after that its just bug testing or whatever but im like 90% sure its all good

**Comment by Subroutine7901** [comment]
Ok I might test tonight idk

**Comment by trinkey** [comment]
im gonna bump version and then poll, i've done quite a bit of testing and it all seems to work well to me

**Pull request merged**
